use jmillf2db;
SET FOREIGN_KEY_CHECKS = 0;
/* 
Drop tables */
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS TAXI;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS PUBLIC_BUS;
DROP TABLE IF EXISTS PRIVATE_BUS;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS BUS_STOP;
DROP TABLE IF EXISTS FARE;
DROP TABLE IF EXISTS STATION;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DRIVER;
DROP TABLE IF EXISTS MECHANIC;
DROP TABLE IF EXISTS JANITOR;
DROP TABLE IF EXISTS CASHIER;
DROP TABLE IF EXISTS HR;
DROP TABLE IF EXISTS SUPERVISER;
DROP TABLE IF EXISTS REPAIR_LOG;

SET FOREIGN_KEY_CHECKS = 1;
